### ISSUE TITLE
Implement some logic in the backend RESTAPI

### ISSUE THREAD

**Issue by JeffOwOSun** [COMP3111H-2015-Fall/questionJS-RESTAPI#2]
# Description

Since we now have a custom RESTAPI background we can implement some of the logic in the backend and alleviate the workload in the frontend code.

# Checklist

- [x] Add echo function
- [x] Complete function
- [x] FBLogin and Logout

# Description

## Add echo
Name | Specification
---------|------------------
URL | api/questions/:question_id/add-echo
VERB | GET
RETURN | The entire questions list after the update is done. Sorted in new order.
REMARKS | The old hack of adding *order* to the todo is no longer needed since NodeJs is capable of sorting in descending order

## Complete a task
Name | Specification
---------|------------------
URL | api/questions/:question_id/complete
VERB | GET
RETURN | The entire questions list after the update.

## FB Login and Logout
Need to refer to the Facebook API. No conclusion.

**Comment by Oh233** [comment]
前排膜拜
